spring.application.name=tfg
server.port=${PORT:8080}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:5432/postgres?user=postgres.viatdrkvnlrlmjxiajyt&password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Madrid

